nginx:
  build: ./nginx-1.8.0
  volumes:
    - ../:/var/www
  links:
    - php:cgi
  ports:
    - "80:80"
    - "443:443"
php:
  build: ./php-5.5.9
  volumes:
    - ../:/var/www
  links:
    - mysql:database
mysql:
  image: mysql:5.6.25
  volumes_from:
    - mysqldata
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=symfony-education
    - MYSQL_USER=developer
    - MYSQL_PASSWORD=developer_password
    - MYSQL_ROOT_PASSWORD=root_password
mysqldata:
  image: ubuntu:14.04.2
  volumes:
    - /var/lib/mysql